language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"

deploy:
  provider: script
  script: npm run release-vscode
  skip_cleanup: true
  on:
    branch: master
    tags: true
